class_name BodyMap

enum Slot {
	HEALTH,
	HEALTH_AUGMENT,
	ATTACK,
	ATTACK_AUGMENT,
	COOLDOWN,
	SPECIALIZATION,
	BREED_AUGMENT,
	NONE
}

enum Stat { HEALTH, ATTACK, COOLDOWN, SPECIALIZATION, BREEDING }

const STAT_SLOTS := {
	Stat.HEALTH: [Slot.HEALTH, Slot.HEALTH_AUGMENT],
	Stat.ATTACK: [Slot.ATTACK, Slot.ATTACK_AUGMENT],
	Stat.COOLDOWN: [Slot.COOLDOWN],
	Stat.SPECIALIZATION: [Slot.SPECIALIZATION],
	Stat.BREEDING: [Slot.BREED_AUGMENT],
}

#This is for the right alleles
enum BuffMode { FLAT, PERCENT, NONE }

const SLOT_BUFF := {
	Slot.HEALTH: BuffMode.FLAT,
	Slot.HEALTH_AUGMENT: BuffMode.PERCENT,
	Slot.ATTACK: BuffMode.FLAT,
	Slot.ATTACK_AUGMENT: BuffMode.PERCENT,
	Slot.COOLDOWN: BuffMode.FLAT,
	Slot.SPECIALIZATION: BuffMode.NONE,
	Slot.BREED_AUGMENT: BuffMode.NONE,
}

enum Part { NONE, FEET, BODY, WINGS, TAIL, HEAD, MISC, EARS, MOUTH, EYES }
